package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/yourorg/sentrix/internal/agent"
	"github.com/yourorg/sentrix/internal/auth"
	"github.com/yourorg/sentrix/internal/database"
	"github.com/yourorg/sentrix/internal/graph/model"
)

// CreateFlow is the resolver for the createFlow field.
func (r *mutationResolver) CreateFlow(ctx context.Context, input model.CreateFlowInput) (*model.Flow, error) {
	uid := currentUserID(ctx)
	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}
	cfg := "{}"
	if input.Config != nil {
		cfg = *input.Config
	}
	flow := database.Flow{
		UserID:      uid,
		Title:       strings.TrimSpace(input.Title),
		Description: strings.TrimSpace(desc),
		Status:      "pending",
		Config:      cfg,
	}
	if err := r.DB.Create(&flow).Error; err != nil {
		return nil, fmt.Errorf("failed to create flow: %w", err)
	}
	return toGQLFlow(flow, r.Scraper), nil
}

// UpdateFlow is the resolver for the updateFlow field.
func (r *mutationResolver) UpdateFlow(ctx context.Context, id uuid.UUID, input model.UpdateFlowInput) (*model.Flow, error) {
	uid := currentUserID(ctx)
	var flow database.Flow
	if err := r.DB.Where("id = ? AND user_id = ?", id, uid).First(&flow).Error; err != nil {
		return nil, fmt.Errorf("flow not found")
	}

	updates := map[string]interface{}{}
	if input.Title != nil {
		updates["title"] = strings.TrimSpace(*input.Title)
	}
	if input.Description != nil {
		updates["description"] = strings.TrimSpace(*input.Description)
	}
	if input.Status != nil {
		updates["status"] = *input.Status
	}
	if input.Config != nil {
		updates["config"] = *input.Config
	}
	if len(updates) > 0 {
		if err := r.DB.Model(&flow).Updates(updates).Error; err != nil {
			return nil, fmt.Errorf("failed to update flow: %w", err)
		}
	}

	r.DB.First(&flow, "id = ?", id)
	return toGQLFlow(flow, r.Scraper), nil
}

// DeleteFlow is the resolver for the deleteFlow field.
func (r *mutationResolver) DeleteFlow(ctx context.Context, id uuid.UUID) (bool, error) {
	uid := currentUserID(ctx)
	result := r.DB.Where("id = ? AND user_id = ?", id, uid).Delete(&database.Flow{})
	return result.RowsAffected > 0, result.Error
}

// StopFlow is the resolver for the stopFlow field.
func (r *mutationResolver) StopFlow(ctx context.Context, id uuid.UUID) (*model.Flow, error) {
	uid := currentUserID(ctx)
	var flow database.Flow
	if err := r.DB.Where("id = ? AND user_id = ?", id, uid).First(&flow).Error; err != nil {
		return nil, fmt.Errorf("flow not found")
	}
	if err := r.DB.Model(&flow).Update("status", "stopped").Error; err != nil {
		return nil, fmt.Errorf("failed to stop flow: %w", err)
	}
	r.DB.First(&flow, "id = ?", id)
	return toGQLFlow(flow, r.Scraper), nil
}

// CreateProvider is the resolver for the createProvider field.
func (r *mutationResolver) CreateProvider(ctx context.Context, input model.CreateProviderInput) (*model.ProviderConfig, error) {
	uid := currentUserID(ctx)
	isDefault := false
	if input.IsDefault != nil {
		isDefault = *input.IsDefault
	}
	if isDefault {
		r.DB.Model(&database.ProviderConfig{}).
			Where("user_id = ? AND provider_type = ?", uid, input.ProviderType).
			Update("is_default", false)
	}

	modelName := ""
	if input.ModelName != nil {
		modelName = *input.ModelName
	}

	provider := database.ProviderConfig{
		UserID:          uid,
		ProviderType:    input.ProviderType,
		ModelName:       modelName,
		APIKeyEncrypted: input.APIKey,
		BaseURL:         input.BaseURL,
		IsDefault:       isDefault,
		Config:          "{}",
	}
	if input.Config != nil {
		provider.Config = *input.Config
	}
	if err := r.DB.Create(&provider).Error; err != nil {
		return nil, fmt.Errorf("failed to create provider: %w", err)
	}
	return toGQLProvider(provider), nil
}

// UpdateProvider is the resolver for the updateProvider field.
func (r *mutationResolver) UpdateProvider(ctx context.Context, id uuid.UUID, input model.UpdateProviderInput) (*model.ProviderConfig, error) {
	uid := currentUserID(ctx)
	var provider database.ProviderConfig
	if err := r.DB.Where("id = ? AND user_id = ?", id, uid).First(&provider).Error; err != nil {
		return nil, fmt.Errorf("provider not found")
	}

	updates := map[string]interface{}{}
	if input.ModelName != nil {
		updates["model_name"] = *input.ModelName
	}
	if input.APIKey != nil {
		updates["api_key_encrypted"] = *input.APIKey
	}
	if input.BaseURL != nil {
		updates["base_url"] = *input.BaseURL
	}
	if input.IsDefault != nil && *input.IsDefault {
		r.DB.Model(&database.ProviderConfig{}).
			Where("user_id = ? AND provider_type = ? AND id != ?", uid, provider.ProviderType, id).
			Update("is_default", false)
		updates["is_default"] = true
	}
	if input.Config != nil {
		updates["config"] = *input.Config
	}

	if len(updates) > 0 {
		if err := r.DB.Model(&provider).Updates(updates).Error; err != nil {
			return nil, fmt.Errorf("failed to update provider: %w", err)
		}
	}

	r.DB.First(&provider, "id = ?", id)
	return toGQLProvider(provider), nil
}

// DeleteProvider is the resolver for the deleteProvider field.
func (r *mutationResolver) DeleteProvider(ctx context.Context, id uuid.UUID) (bool, error) {
	uid := currentUserID(ctx)
	result := r.DB.Where("id = ? AND user_id = ?", id, uid).Delete(&database.ProviderConfig{})
	return result.RowsAffected > 0, result.Error
}

// CreateAPIToken is the resolver for the createAPIToken field.
func (r *mutationResolver) CreateAPIToken(ctx context.Context, input model.CreateAPITokenInput) (*model.CreateAPITokenPayload, error) {
	uid := currentUserID(ctx)
	rawToken, tokenHash, err := auth.GenerateAPIToken()
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	tok := database.APIToken{
		UserID:    uid,
		Label:     strings.TrimSpace(input.Label),
		TokenHash: tokenHash,
	}
	if err := r.DB.Create(&tok).Error; err != nil {
		return nil, fmt.Errorf("failed to store token: %w", err)
	}

	return &model.CreateAPITokenPayload{
		Token: rawToken,
		Data:  toGQLToken(tok),
	}, nil
}

// DeleteAPIToken is the resolver for the deleteAPIToken field.
func (r *mutationResolver) DeleteAPIToken(ctx context.Context, id uuid.UUID) (bool, error) {
	uid := currentUserID(ctx)
	result := r.DB.Where("id = ? AND user_id = ?", id, uid).Delete(&database.APIToken{})
	return result.RowsAffected > 0, result.Error
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	uid := currentUserID(ctx)
	if uid == uuid.Nil {
		return nil, fmt.Errorf("not authenticated")
	}
	var u database.User
	if err := r.DB.First(&u, "id = ?", uid).Error; err != nil {
		return nil, fmt.Errorf("user not found")
	}
	return &model.User{
		ID:          u.ID,
		Email:       u.Email,
		DisplayName: u.DisplayName,
		Role:        u.Role,
		CreatedAt:   u.CreatedAt,
	}, nil
}

// Flows is the resolver for the flows field.
func (r *queryResolver) Flows(ctx context.Context) ([]*model.Flow, error) {
	uid := currentUserID(ctx)
	var flows []database.Flow
	if err := r.DB.Where("user_id = ?", uid).Order("created_at DESC").Find(&flows).Error; err != nil {
		return nil, err
	}
	result := make([]*model.Flow, len(flows))
	for i, f := range flows {
		result[i] = toGQLFlow(f, r.Scraper)
	}
	return result, nil
}

// Flow is the resolver for the flow field.
func (r *queryResolver) Flow(ctx context.Context, id uuid.UUID) (*model.Flow, error) {
	uid := currentUserID(ctx)
	var f database.Flow
	if err := r.DB.Where("id = ? AND user_id = ?", id, uid).First(&f).Error; err != nil {
		return nil, fmt.Errorf("flow not found")
	}
	return toGQLFlow(f, r.Scraper), nil
}

// Providers is the resolver for the providers field.
func (r *queryResolver) Providers(ctx context.Context) ([]*model.ProviderConfig, error) {
	uid := currentUserID(ctx)
	var providers []database.ProviderConfig
	if err := r.DB.Where("user_id = ?", uid).Order("created_at DESC").Find(&providers).Error; err != nil {
		return nil, err
	}
	result := make([]*model.ProviderConfig, len(providers))
	for i, p := range providers {
		result[i] = toGQLProvider(p)
	}
	return result, nil
}

// APITokens is the resolver for the apiTokens field.
func (r *queryResolver) APITokens(ctx context.Context) ([]*model.APIToken, error) {
	uid := currentUserID(ctx)
	var tokens []database.APIToken
	if err := r.DB.Where("user_id = ?", uid).Order("created_at DESC").Find(&tokens).Error; err != nil {
		return nil, err
	}
	result := make([]*model.APIToken, len(tokens))
	for i, t := range tokens {
		result[i] = toGQLToken(t)
	}
	return result, nil
}

// FlowProgress is the resolver for the flowProgress field.
func (r *subscriptionResolver) FlowProgress(ctx context.Context, flowID uuid.UUID) (<-chan *model.FlowEvent, error) {
	fid := flowID.String()
	eventCh := r.Broadcaster.Subscribe(fid)
	out := make(chan *model.FlowEvent, 64)

	go func() {
		defer r.Broadcaster.Unsubscribe(fid, eventCh)
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-eventCh:
				if !ok {
					return
				}
				fe := agentEventToFlowEvent(evt)
				select {
				case out <- fe:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// ActionOutput is the resolver for the actionOutput field.
func (r *subscriptionResolver) ActionOutput(ctx context.Context, flowID uuid.UUID) (<-chan *model.ActionEvent, error) {
	fid := flowID.String()
	eventCh := r.Broadcaster.Subscribe(fid)
	out := make(chan *model.ActionEvent, 64)

	go func() {
		defer r.Broadcaster.Unsubscribe(fid, eventCh)
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-eventCh:
				if !ok {
					return
				}
				// Only forward action/tool events.
				if evt.Type != agent.EventActionCompleted && evt.Type != agent.EventToolExecuted {
					continue
				}
				ae := agentEventToActionEvent(evt)
				select {
				case out <- ae:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
